---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: chakraview-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: chakraview-dev
  chart:
    git: git@github.com:munishmalhotra/gitops-chakraview.git
    path: charts/chakraview
    ref: master
  values:
    image: walmartcontainerregistry.azurecr.io/cxo:dev-20190117.1
    replicaCount: 1
    hpa:
      enabled: false
